# Generated by Django 4.2 on 2025-11-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeometryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carriageway_width', models.FloatField()),
                ('girder_spacing', models.FloatField()),
                ('num_girders', models.IntegerField()),
                ('deck_overhang_width', models.FloatField()),
                ('overall_width', models.FloatField()),
                ('valid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Geometry Data',
                'verbose_name_plural': 'Geometry Data',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('girder_steel', models.CharField(choices=[('E250', 'E250 (250 MPa)'), ('E350', 'E350 (350 MPa)'), ('E450', 'E450 (450 MPa)')], default='E250', max_length=10)),
                ('cross_bracing_steel', models.CharField(choices=[('E250', 'E250 (250 MPa)'), ('E350', 'E350 (350 MPa)'), ('E450', 'E450 (450 MPa)')], default='E250', max_length=10)),
                ('deck_concrete', models.CharField(choices=[('M25', 'M25 (25 MPa)'), ('M30', 'M30 (30 MPa)'), ('M35', 'M35 (35 MPa)'), ('M40', 'M40 (40 MPa)'), ('M45', 'M45 (45 MPa)'), ('M50', 'M50 (50 MPa)'), ('M55', 'M55 (55 MPa)'), ('M60', 'M60 (60 MPa)')], default='M25', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Material Input',
                'verbose_name_plural': 'Material Inputs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LocationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('basic_wind_speed', models.FloatField()),
                ('seismic_zone', models.CharField(max_length=50)),
                ('seismic_factor', models.FloatField()),
                ('temperature_max', models.FloatField()),
                ('temperature_min', models.FloatField()),
            ],
            options={
                'verbose_name': 'Location Data',
                'verbose_name_plural': 'Location Data',
                'ordering': ['state', 'district'],
                'unique_together': {('state', 'district')},
            },
        ),
    ]
